import type { NextPage } from "next";
import Head from "next/head";

const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> uid Síða!</h1>
    </div>
  );
};

export default Page;
