import { asText } from "@prismicio/helpers";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { fetchFromPrismic } from "../api/prismic";

type PrismicRichText = any;

type Homepage = {
  title?: PrismicRichText;
  content?: PrismicRichText;
  pages?: Array<{
    page?: {
      title?: PrismicRichText;
      _meta: {
        uid: string;
      };
    };
  }>;
};

type PrismicResponse = {
  allHomepages?: {
    edges?: Array<{
      node?: Homepage;
    }>;
  };
};

type Props = {
  page: Homepage;
};
const Home: NextPage<Props> = ({ page }) => {
  const title = asText(page.title);
  return (
    <div>
      <Head>
        <title>{title || "Heimasíða"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{title || "Heimasíða!"}</h1>
    </div>
  );
};

export default Home;

const query = `
query{
  allHomepages {
    edges {
      node {
        title
        content
        pages{
          page{
          	...on Page{
              title
              _meta {
                uid
              }
            }
          }
        }
      }
    }
  }
}
`;

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const result = await fetchFromPrismic<PrismicResponse>(query);
  if (
    !result ||
    !result.allHomepages?.edges ||
    !result.allHomepages.edges[0].node
  ) {
    return {
      notFound: true,
    };
  }
  const page: Homepage = result.allHomepages.edges[0].node;
  return {
    props: {
      page,
    },
  };
};
